version: "3"

services:
  sonarqube:
    image: sonarqube:9.9.1-community
    container_name: sonarqube
    restart: always
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonarqube-db:5432/sonarqube
      - SONAR_JDBC_USERNAME=sonarqube
      - SONAR_JDBC_PASSWORD=sonarqube
      - SONAR_JDBC_MAXACTIVE=50
      - SONAR_JDBC_MAXIDLE=5
      - SONAR_JDBC_MINIDLE=2
    depends_on:
      - sonarqube-db
    networks:
      - sonarnet
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs

  sonarqube-db:
    image: postgres:13.11-alpine
    container_name: sonarqube-db
    restart: always
    environment:
      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=sonarqube
      - POSTGRES_DB=sonarqube
    networks:
      - sonarnet
    volumes:
      - sonarqube_db:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_extensions:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_db:

