version: '3.9'
services:
  emqx:
    image: 'emqx/emqx:5.5.1'
    restart: always
    container_name: emqx
    ports:
      - '18083:18083'
      - '8883:8883'
      - '8084:8084'
      - '8083:8083'
      - '1883:1883'
    volumes:
      - ./data:/opt/emqx/data
      - ./log:/opt/emqx/log
