version: '3.7'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    container_name: elasticsearch
    environment:
      # xpack.security.enabled设置为false，表示禁止xpack
      - xpack.security.enabled=false
      - discovery.type=single-node
      # ES_JAVA_OPTS=-Xms512m -Xmx512m设置ES允许的jvm大小
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
      - ./elasticsearch-plugins:/usr/share/elasticsearch/plugins
    ports:
      # 9200作为Http协议，主要用于外部通讯，9300作为Tcp协议，jar之间就是通过tcp协议通讯，ES集群之间是通过9300进行通讯
      - 9200:9200
      - 9300:9300
    networks:
      - elastic


volumes:
  elasticsearch-data:
    driver: local
  elasticsearch-plugins:
    driver: local

networks:
  elastic:
    driver: bridge