version: '3.2'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_DB=nextcloud # 需要先`docker-compose up db` `docker-compose down` 然后`docker-compose up`
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud

  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    volumes:
      - /data1/nextcloud:/var/www/html:rw
      - /data1/public:/home:rw
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
      - NEXTCLOUD_ADMIN_PASSWORD=nextcloud
      - NEXTCLOUD_ADMIN_USER=nextcloud
    depends_on:
      - db