version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.12.14-management
    container_name: rabbitmq
    restart: always
    #hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
