services:
  jupyterlab:
    image: jupyter/scipy-notebook:x86_64-ubuntu-22.04
    user: root # 需要root启动才可以自定义目录
    restart: always
    container_name: jupyterlab
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]
    ports:
      - 8888:8888
    environment:
      - NVIDIA_VISIBLE_DEVICES= # 配置显卡id
      - NB_USER=wangjiahao # 变成/home/wangjiahao
      - CHOWN_HOME=yes # 是否改变工作目录
      - TZ=Asia/Shanghai
    working_dir: /home/wangjiahao # 指定工作目录
    volumes:
      - ./data:/home/wangjiahao # 挂载目录
