version: '3'
services:
  jupyterlab:
    image: jupyter/scipy-notebook
    user: root # 需要root启动才可以自定义目录
    restart: always
    container_name: jupyterlab
    ports:
      - 8888:8888
    environment:
      - NB_USER=wangjiahao # 变成/home/wangjiahao
      - CHOWN_HOME=yes # 是否改变工作目录
      - TZ=Asia/Shanghai
    working_dir: /home/wangjiahao # 指定工作目录
    volumes:
      - ./data:/home/wangjiahao # 挂载目录
