# Use root/example as user/password credentials
version: '3'

services:
  mongo:
    image: mongo:5.0.21
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      TZ: Asia/Shanghai
#      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    command: [--auth] # 指定需要认证，mongdb默认是无认证的
    volumes:
      - ./data:/data/db
      - ./configdb:/data/configdb
#      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
