version: '3'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      SA_PASSWORD: YourStrongPassword123
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/mssql
