version: "3.9"

services:
  gitlab-runner:
    image: gitlab/gitlab-runner:v16.10.0
    container_name: gitlab-runner
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock' # 这个挂载是将宿主机上的docker socket挂载到了容器内，这样容器内执行的docker命令会被宿主机docker daemon最终执行。
      - '/srv/gitlab-runner/config:/etc/gitlab-runner' # 这个挂载是将gitlab-runner的配置文件挂载到宿主机上，这样我们可以通过修改宿主机上的这个配置文件对gitlab-runner进行配置
