version: '3'
services:
  nginx:
    image: nginx:1.27.4-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # 预先准备nginx.conf
      - ./conf.d:/etc/nginx/conf.d:ro # 为了更好的扩展配置
      - ./html:/usr/share/nginx/html:ro # 页面主要入口
