services:
  elasticsearch:
    image: elasticsearch:7.10.1
    container_name: elasticsearch
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      # 9200作为Http协议，主要用于外部通讯，9300作为Tcp协议，jar之间就是通过tcp协议通讯，ES集群之间是通过9300进行通讯
      - "9200:9200"
      - "9300:9300"
    environment:
      TZ: Asia/Shanghai
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      ELASTIC_PASSWORD: "YourStrongPassword123!"  # 设置elastic用户密码
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./data:/usr/share/elasticsearch/data:rw
      - ./logs:/usr/share/elasticsearch/logs:rw
      - ./plugins:/usr/share/elasticsearch/plugins:rw
      # 挂在下面3个可能有问题，还没排查
      #- ./certs:/usr/share/elasticsearch/config/certs:rw  # 证书目录
      #- ./ingest-pipelines:/usr/share/elasticsearch/config/ingest-pipelines:rw  # 地理处理管道
      #- ./dictionaries:/usr/share/elasticsearch/config/dictionaries:rw  # IK自定义词典目录
