version: '3'
services:
  mysql:
    restart: always
    image: mysql:8.0.31
    container_name: mysql8
    ports:
      - "3306:3306"
    environment:
      #- "MYSQL_USER: user" # 创建新用户
      - "MYSQL_ROOT_PASSWORD=123456"
      #- "MYSQL_DATABASE=mydb" # 创建新的库
      - "TZ=Asia/Shanghai"
    volumes:
      - ./data:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d # 特性配置文件命名 xx.cnf aa.cnf bb.cnf cc.cnf
      - ./logs:/logs
