version: '3'
services:
  mysql:
    restart: always
    image: mysql:8.0.20
    container_name: MYSQL8
    ports:
      - 3306:3306
    environment:
#      - MYSQL_USER: user # 创建新用户
      - "MYSQL_ROOT_PASSWORD=123456"
#      - "MYSQL_DATABASE=mydb" # 创建新的库
      - "TZ=Asia/Shanghai"
    volumes:
      - /data/mysql/data:/var/lib/mysql
      - /data/mysql/conf:/etc/mysql/conf.d
      - ~/data/mysql/logs:/logs