services:
  mysql:
    restart: always
    image: mysql:8.4.4
    container_name: mysql
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.5'
    #       memory: 512M
    ports:
      - "3306:3306"
    environment:
      #- "MYSQL_USER: user" # 创建新用户
      - "MYSQL_ROOT_PASSWORD=123456"
      #- "MYSQL_DATABASE=mydb" # 创建新的库
      - "TZ=Asia/Shanghai"
    # 忽律表名大小写
#    command: --lower-case-table-names=1
    volumes:
      - ./data:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d # 特性配置文件命名 xx.cnf aa.cnf bb.cnf cc.cnf
      - ./logs:/logs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
