version: '3'
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always
    command: server --console-address ':9001' /data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin1234 # 大于等于8位
#    logging:
#      options:
#        max-size: "50M" # 最大文件上传限制
#        max-file: "10"
#      driver: json-file
    volumes:
      - /data/minio/data:/data # 映射文件路径
      - /data/minio/config:/root/.minio # 映射配置文件
#    network_mode: bridge
