version: '3.1'
services:
  postgresql:
    restart: always
    image: postgres:14.2
    container_name: postgresql
    ports:
      - 5432:5432
    env_file:
      - ".env"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./data:/var/lib/postgres/data