services:
  postgresql:
    restart: always
    image: pgvector/pgvector:pg16
    container_name: postgresql
    ports:
      - "5432:5432"
    env_file:
      - ".env"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./data:/var/lib/postgresql/data
