version: '3'
services:
  redis:
    image: redis:6.2.5
    restart: always
    container_name: redis
    ports:
      - 6379:6379
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - /data/redis/data:/data
      - /data/redis/conf/redis.conf:/etc/redis/redis.conf # 配置文件，暂时不需要
      - /data/redis/logs:/logs