version: '3'
services:
  redis:
    image: redis:6.2.5
    restart: always
    container_name: redis
    ports:
      - 6379:6379
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./data:/data
      - ./config:/etc/redis # 在当前目录下创建 vim config/redis.conf 配置文件，并写入配置，不需要可以注释
      - ./logs:/logs
